Repository coordinape/coordinape, pull requests merged in 2022-02, with the labels that each got.

#501 adds utc zone to nextRepeat date on AdminEpochForm
  src/forms/AdminEpochForm.tsx
Labels: bug, 1

#504 Adds types utils for stories
  .storybook/main.js
  package.json
  src/ui/Button/Button.stories.tsx
  src/ui/Button/Button.tsx
  src/ui/Divider/Divider.tsx
  src/ui/IconButton/IconButton.tsx
  src/ui/TextArea/TextArea.tsx
  src/ui/TextField/TextField.stories.tsx
  src/ui/TextField/TextField.tsx
  src/ui/type-utils.ts
  yarn.lock
Labels: enhancement, 3

#526 fix spoofing address issue for create circle
  .env.example
  api-lib/Gql.ts
  api-lib/circleAdmin.ts
  api-lib/config.ts
  api-lib/findUser.ts
  api-lib/validate.ts
  api/hasura/actions/create_circle.ts
  api/hasura/auth.ts
  docker-compose.yml
  hasura/metadata/actions.graphql
  hasura/metadata/actions.yaml
  src/lib/gql/GqlHasuraAdmin.ts
  src/lib/gql/zeusHasuraAdmin/const.ts
  src/lib/gql/zeusHasuraAdmin/index.ts
  src/lib/gql/zeusUser/const.ts
  src/lib/gql/zeusUser/index.ts
  src/lib/zod/index.ts
  tsconfig.json
Labels: Ready For Review

#530 Adds Claim Card
  src/components/ClaimCard/ClaimCard.stories.tsx
  src/components/ClaimCard/ClaimCard.test.tsx
  src/components/ClaimCard/ClaimCard.tsx
  src/pages/DistributePage/DistributePage.tsx
  src/stitches.config.ts
  src/ui/Button/Button.tsx
  src/ui/Panel/Panel.tsx
  src/ui/Text/Text.tsx
  src/ui/icons/ArrowDownLeftIcon.tsx
  src/ui/icons/index.ts
  src/ui/index.ts
Labels: good first issue, 3

#537 Spike/stitches svg icon
  src/components/ClaimCard/ClaimCard.tsx
  src/ui/Button/Button.tsx
  src/ui/SvgIcon/SvgIcon.tsx
  src/ui/Text/Text.tsx
  src/ui/icons/ArrowDownLeftIcon.tsx
  src/ui/icons/SvgIcon.stories.tsx
  src/ui/index.ts
Labels: 3

#516 Setup Hasura preview to point to Vercel preview for Action Handlers
  .github/workflows/hasura-preview.yml
Labels: Ready For Review

#520 Script to consume and generate colors from figma API
  .env.example
  package.json
  scripts/update-figma-colors.ts
  src/ui/colors.ts
  yarn.lock
Labels: 5
